name: react-flask-postgres

services:

  frontend:
    image: frontend
    build: ./react-crud
    environment:
      - PROXY_PORT=6969
    networks:
      - client-side
    ports:
      - 3000:3000
    depends_on:
      - backend
      - db
      - setup

  proxy:
    image: proxy
    build: ./proxy-server
    environment:
      - TARGET_HOST=backend
      - TARGET_PORT=8000
    networks: 
      - client-side
      - server-side
    ports:
      - 6969:6969
    

  backend:
    image: backend
    build: ./flask_app
    environment:
      - DBNAME=postgres
      - DBHOST=db
      - DBUSER=postgres
      - DBPASSWORD=mysecretpassword
      - DBPORT=5432
    networks:
      # - client-side
      - server-side
    depends_on:
      - db
      - setup

  db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    networks:
      - server-side
    ports:
      - 5432:5432
    # volumes:
      # - db-data:/var/lib/postgresql/data

  # Data Adder
  setup:
    image: setup
    build: setup
    environment:
      - DBPORT=5432
      - DBNAME=postgres
      - DBHOST=db
      - DBUSER=postgres
      - DBPASSWORD=mysecretpassword
      - WAIT_HOSTS=db:5432
    networks:
      - server-side

networks:
  client-side: {}
  server-side: {}

volumes:
  backend-cache: {}
  db-data: {}